version: "3.3"
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "tiny_exchange_test_db"
      POSTGRES_USER: "nikita"
      POSTGRES_PASSWORD: "nikita2209"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5433:5433"